<a href="https://colab.research.google.com/github/Samia35-2973/Machine-Learning-Notes/blob/main/hiring.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
!pip install word2number

Requirement already satisfied: word2number in /usr/local/lib/python3.10/dist-packages (1.1)

In [ ]:
import matplotlib.pyplot as plt
import numpy as np
import pandas as pd
import math
from sklearn import linear_model
from word2number import w2n # for converting word to number

In [ ]:
df = pd.read_csv('hiring.csv')
df

  experience  test_score(out of 10)  interview_score(out of 10)  salary($)
0        NaN                    8.0                           9      50000
1        NaN                    8.0                           6      45000
2       five                    6.0                           7      60000
3        two                   10.0                          10      65000
4      seven                    9.0                           6      70000
5      three                    7.0                          10      62000
6        ten                    NaN                           7      72000
7     eleven                    7.0                           8      80000

In [ ]:
df.isna()

   experience  test_score(out of 10)  interview_score(out of 10)  salary($)
0        True                  False                       False      False
1        True                  False                       False      False
2       False                  False                       False      False
3       False                  False                       False      False
4       False                  False                       False      False
5       False                  False                       False      False
6       False                   True                       False      False
7       False                  False                       False      False

In [ ]:
# Since experience has also string value so null values can be stated as 'zero'
df.experience = df.experience.fillna('zero')
df

  experience  test_score(out of 10)  interview_score(out of 10)  salary($)
0       zero                    8.0                           9      50000
1       zero                    8.0                           6      45000
2       five                    6.0                           7      60000
3        two                   10.0                          10      65000
4      seven                    9.0                           6      70000
5      three                    7.0                          10      62000
6        ten                    NaN                           7      72000
7     eleven                    7.0                           8      80000

In [ ]:
# convert the words to number
df.experience = df.experience.apply(w2n.word_to_num)

In [ ]:
# Since there are lot of data mean is prefered

df[['test_score(out of 10)']] = df[['test_score(out of 10)']].fillna(math.floor(df[['test_score(out of 10)']].mean()))
df

   experience  test_score(out of 10)  interview_score(out of 10)  salary($)
0           0                    8.0                           9      50000
1           0                    8.0                           6      45000
2           5                    6.0                           7      60000
3           2                   10.0                          10      65000
4           7                    9.0                           6      70000
5           3                    7.0                          10      62000
6          10                    7.0                           7      72000
7          11                    7.0                           8      80000

In [ ]:
reg = linear_model.LinearRegression()
reg.fit(df[['experience', 'test_score(out of 10)', 'interview_score(out of 10)']], df[['salary($)']])

LinearRegression()

In [ ]:
reg.coef_

array([[2922.26901502, 2221.30909959, 2147.48256637]])

In [ ]:
reg.intercept_

array([14992.65144669])

In [ ]:
reg.predict([[2, 9, 6]])

/usr/local/lib/python3.10/dist-packages/sklearn/base.py:439: UserWarning: X does not have valid feature names, but LinearRegression was fitted with feature names
  warnings.warn(

array([[53713.86677124]])

In [ ]:
reg.predict([[12, 10, 10]])

/usr/local/lib/python3.10/dist-packages/sklearn/base.py:439: UserWarning: X does not have valid feature names, but LinearRegression was fitted with feature names
  warnings.warn(

array([[93747.79628651]])