<a href="https://colab.research.google.com/github/Samia35-2973/Machine-Learning-Notes/blob/main/one_hot_encoding_linear_regression_exercise.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [210]:
import pandas as pd
import numpy as np
from sklearn import linear_model
from sklearn.preprocessing import LabelEncoder
from sklearn.preprocessing import OneHotEncoder
from sklearn.compose import ColumnTransformer

In [211]:
df = pd.read_csv('carprices.csv')
df

                Car Model  Mileage  Sell Price($)  Age(yrs)
0                  BMW X5    69000          18000         6
1                  BMW X5    35000          34000         3
2                  BMW X5    57000          26100         5
3                  BMW X5    22500          40000         2
4                  BMW X5    46000          31500         4
5                 Audi A5    59000          29400         5
6                 Audi A5    52000          32000         5
7                 Audi A5    72000          19300         6
8                 Audi A5    91000          12000         8
9   Mercedez Benz C class    67000          22000         6
10  Mercedez Benz C class    83000          20000         7
11  Mercedez Benz C class    79000          21000         7
12  Mercedez Benz C class    59000          33000         5

In [212]:
dummies = pd.get_dummies(df[['Car Model']])
dummies

    Car Model_Audi A5  Car Model_BMW X5  Car Model_Mercedez Benz C class
0                   0                 1                                0
1                   0                 1                                0
2                   0                 1                                0
3                   0                 1                                0
4                   0                 1                                0
5                   1                 0                                0
6                   1                 0                                0
7                   1                 0                                0
8                   1                 0                                0
9                   0                 0                                1
10                  0                 0                                1
11                  0                 0                                1
12                  0                 0                                1

In [213]:
df = pd.concat([df, dummies], axis='columns')
df

,Car Model,Mileage,Sell Price($),Age(yrs),Car Model_Audi A5,Car Model_BMW X5,Car Model_Mercedez Benz C class
0,BMW X5,69000,18000,6,0,1,0
1,BMW X5,35000,34000,3,0,1,0
2,BMW X5,57000,26100,5,0,1,0
3,BMW X5,22500,40000,2,0,1,0
4,BMW X5,46000,31500,4,0,1,0
5,Audi A5,59000,29400,5,1,0,0
6,Audi A5,52000,32000,5,1,0,0
7,Audi A5,72000,19300,6,1,0,0
8,Audi A5,91000,12000,8,1,0,0
9,Mercedez Benz C class,67000,22000,6,0,0,1
10,Mercedez Benz C class,83000,20000,7,0,0,1
11,Mercedez Benz C class,79000,21000,7,0,0,1
12,Mercedez Benz C class,59000,33000,5,0,0,1

In [214]:
df = df.drop(['Car Model', 'Car Model_Audi A5'], axis='columns')
df

,Mileage,Sell Price($),Age(yrs),Car Model_BMW X5,Car Model_Mercedez Benz C class
0,69000,18000,6,1,0
1,35000,34000,3,1,0
2,57000,26100,5,1,0
3,22500,40000,2,1,0
4,46000,31500,4,1,0
5,59000,29400,5,0,0
6,52000,32000,5,0,0
7,72000,19300,6,0,0
8,91000,12000,8,0,0
9,67000,22000,6,0,1
10,83000,20000,7,0,1
11,79000,21000,7,0,1
12,59000,33000,5,0,1

In [215]:
y = df[['Sell Price($)']]
y

    Sell Price($)
0           18000
1           34000
2           26100
3           40000
4           31500
5           29400
6           32000
7           19300
8           12000
9           22000
10          20000
11          21000
12          33000

In [216]:
x = df.drop(['Sell Price($)'], axis='columns')
x

    Mileage  Age(yrs)  Car Model_BMW X5  Car Model_Mercedez Benz C class
0     69000         6                 1                                0
1     35000         3                 1                                0
2     57000         5                 1                                0
3     22500         2                 1                                0
4     46000         4                 1                                0
5     59000         5                 0                                0
6     52000         5                 0                                0
7     72000         6                 0                                0
8     91000         8                 0                                0
9     67000         6                 0                                1
10    83000         7                 0                                1
11    79000         7                 0                                1
12    59000         5                 0                                1

In [217]:
model = linear_model.LinearRegression()
model.fit(x,y)

LinearRegression()

In [218]:
# Predict price of a mercedez benz that is 4 yr old with mileage 45000
model.predict([[45000, 4, 0, 1]])

/usr/local/lib/python3.10/dist-packages/sklearn/base.py:439: UserWarning: X does not have valid feature names, but LinearRegression was fitted with feature names
  warnings.warn(

array([[36991.31721061]])

In [219]:
# Predict price of a BMW X5 that is 7 yr old with mileage 86000
model.predict([[86000, 7, 1, 0]])

/usr/local/lib/python3.10/dist-packages/sklearn/base.py:439: UserWarning: X does not have valid feature names, but LinearRegression was fitted with feature names
  warnings.warn(

array([[11080.74313219]])

In [220]:
model.score(x,y)

0.9417050937281083

In [221]:
le = LabelEncoder()

In [222]:
d = pd.read_csv('carprices.csv')
dle = d
dle['Car Model'] = le.fit_transform(dle['Car Model'])
dle

    Car Model  Mileage  Sell Price($)  Age(yrs)
0           1    69000          18000         6
1           1    35000          34000         3
2           1    57000          26100         5
3           1    22500          40000         2
4           1    46000          31500         4
5           0    59000          29400         5
6           0    52000          32000         5
7           0    72000          19300         6
8           0    91000          12000         8
9           2    67000          22000         6
10          2    83000          20000         7
11          2    79000          21000         7
12          2    59000          33000         5

In [223]:
X = dle[['Car Model', 'Mileage', 'Age(yrs)']].values
X

array([[    1, 69000,     6],
       [    1, 35000,     3],
       [    1, 57000,     5],
       [    1, 22500,     2],
       [    1, 46000,     4],
       [    0, 59000,     5],
       [    0, 52000,     5],
       [    0, 72000,     6],
       [    0, 91000,     8],
       [    2, 67000,     6],
       [    2, 83000,     7],
       [    2, 79000,     7],
       [    2, 59000,     5]])

In [224]:
Y = dle[['Sell Price($)']].values
Y

array([[18000],
       [34000],
       [26100],
       [40000],
       [31500],
       [29400],
       [32000],
       [19300],
       [12000],
       [22000],
       [20000],
       [21000],
       [33000]])

In [225]:
ohe = OneHotEncoder()
ct = ColumnTransformer([('Car Model', ohe, [0])], remainder='passthrough')

In [226]:
X = ct.fit_transform(X)
X

array([[0.00e+00, 1.00e+00, 0.00e+00, 6.90e+04, 6.00e+00],
       [0.00e+00, 1.00e+00, 0.00e+00, 3.50e+04, 3.00e+00],
       [0.00e+00, 1.00e+00, 0.00e+00, 5.70e+04, 5.00e+00],
       [0.00e+00, 1.00e+00, 0.00e+00, 2.25e+04, 2.00e+00],
       [0.00e+00, 1.00e+00, 0.00e+00, 4.60e+04, 4.00e+00],
       [1.00e+00, 0.00e+00, 0.00e+00, 5.90e+04, 5.00e+00],
       [1.00e+00, 0.00e+00, 0.00e+00, 5.20e+04, 5.00e+00],
       [1.00e+00, 0.00e+00, 0.00e+00, 7.20e+04, 6.00e+00],
       [1.00e+00, 0.00e+00, 0.00e+00, 9.10e+04, 8.00e+00],
       [0.00e+00, 0.00e+00, 1.00e+00, 6.70e+04, 6.00e+00],
       [0.00e+00, 0.00e+00, 1.00e+00, 8.30e+04, 7.00e+00],
       [0.00e+00, 0.00e+00, 1.00e+00, 7.90e+04, 7.00e+00],
       [0.00e+00, 0.00e+00, 1.00e+00, 5.90e+04, 5.00e+00]])

In [227]:
X = X[:,1:]
X

array([[1.00e+00, 0.00e+00, 6.90e+04, 6.00e+00],
       [1.00e+00, 0.00e+00, 3.50e+04, 3.00e+00],
       [1.00e+00, 0.00e+00, 5.70e+04, 5.00e+00],
       [1.00e+00, 0.00e+00, 2.25e+04, 2.00e+00],
       [1.00e+00, 0.00e+00, 4.60e+04, 4.00e+00],
       [0.00e+00, 0.00e+00, 5.90e+04, 5.00e+00],
       [0.00e+00, 0.00e+00, 5.20e+04, 5.00e+00],
       [0.00e+00, 0.00e+00, 7.20e+04, 6.00e+00],
       [0.00e+00, 0.00e+00, 9.10e+04, 8.00e+00],
       [0.00e+00, 1.00e+00, 6.70e+04, 6.00e+00],
       [0.00e+00, 1.00e+00, 8.30e+04, 7.00e+00],
       [0.00e+00, 1.00e+00, 7.90e+04, 7.00e+00],
       [0.00e+00, 1.00e+00, 5.90e+04, 5.00e+00]])

In [228]:
model.fit(X, Y)

LinearRegression()

In [229]:
# Predict price of a mercedez benz that is 4 yr old with mileage 45000
model.predict([[0, 1, 45000, 4]])

array([[36991.31721062]])

In [230]:
# Predict price of a BMW X5 that is 7 yr old with mileage 86000
model.predict([[1, 0, 86000, 7]])

array([[11080.74313219]])

In [231]:
model.score(X,Y)

0.9417050937281082